DROP TABLE IF EXISTS plan;

CREATE TABLE plan (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PLANS VARCHAR(255) NOT NULL
);

INSERT INTO plan ('PLANS') VALUES ('CHERNOBYL');
INSERT INTO plan ('PLANS') VALUES ('SIBERIA');